# Generated by Django 3.0.6 on 2020-07-08 06:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('num', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(max_length=256)),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Limit')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='LimitMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sybsidy_code', models.CharField(max_length=5)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('industry_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.IndustryCode')),
            ],
            options={
                'ordering': ['sybsidy_code'],
            },
        ),
        migrations.CreateModel(
            name='LimitDateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Limit')),
            ],
        ),
        migrations.CreateModel(
            name='LimitArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('num', models.PositiveSmallIntegerField(db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Source')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.AddField(
            model_name='industrycode',
            name='limit_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.LimitArticle'),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='limits.LimitArticle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='limitdateinfo',
            constraint=models.UniqueConstraint(fields=('limit', 'date'), name='limit_and_date'),
        ),
    ]
