# Generated by Django 2.1.7 on 2019-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('num', models.CharField(db_index=True, max_length=30, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год')),
            ],
        ),
        migrations.CreateModel(
            name='LimitArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статья')),
                ('num', models.PositiveSmallIntegerField(db_index=True, verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='LimitMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('sybsidy_code', models.CharField(max_length=5, verbose_name='Код субсидии')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Сумма средств')),
                ('industry_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.IndustryCode', verbose_name='Отраслевой код')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(db_index=True, verbose_name='КФО')),
                ('name', models.CharField(max_length=30, verbose_name='Источник')),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Limit', verbose_name='Год лимитов')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('num', models.CharField(db_index=True, max_length=4, verbose_name='Код')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Сумма')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Source', verbose_name='Источник')),
            ],
        ),
        migrations.AddField(
            model_name='limitarticle',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='industrycode',
            name='limit_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.LimitArticle', verbose_name='Статья'),
        ),
    ]
