# Generated by Django 2.1.7 on 2019-04-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrycode',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='limitarticle',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='limitmoney',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименование'),
        ),
    ]
