# Generated by Django 2.1.7 on 2019-04-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0002_auto_20190416_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrycode',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='limit',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='limitarticle',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='limitmoney',
            options={'ordering': ['sybsidy_code']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['num']},
        ),
    ]
