# Generated by Django 2.2.3 on 2019-11-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0003_auto_20190429_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('source', models.IntegerField(verbose_name='Источник')),
                ('article', models.IntegerField(verbose_name='Статья')),
                ('industry_code', models.CharField(max_length=50, verbose_name='Отраслевой код')),
                ('sybsidy_code', models.CharField(max_length=50, verbose_name='Код субсидии')),
            ],
        ),
    ]
