# Generated by Django 3.0.6 on 2020-05-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0004_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='industry_code',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='source',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='sybsidy_code',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='year',
        ),
        migrations.AddField(
            model_name='debt',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='limits.LimitArticle', verbose_name='Статья'),
        ),
    ]
