# Generated by Django 3.0.6 on 2020-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0005_auto_20200514_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Наименование'),
        ),
    ]
