# Generated by Django 2.1.7 on 2019-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма изменения цены')),
            ],
        ),
        migrations.CreateModel(
            name='StartPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма')),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.LimitMoney', verbose_name='Лимиты')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Subdivision', verbose_name='Подраздел')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
