# Generated by Django 2.1.7 on 2019-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limits', '0001_initial'),
        ('tenders', '0001_initial'),
        ('contracts', '0001_initial'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startprice',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.Tender', verbose_name='Закупка'),
        ),
        migrations.AddField(
            model_name='contractpricechange',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.ContractChange', verbose_name='Доп. соглашение'),
        ),
        migrations.AddField(
            model_name='contractpricechange',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.ContractPrice', verbose_name='Цена контракта'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Контракт'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.LimitMoney', verbose_name='Лимиты'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='start_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prices.StartPrice', verbose_name='НМЦК'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limits.Subdivision', verbose_name='Подраздел'),
        ),
    ]
