# Generated by Django 2.1.7 on 2019-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Сумма')),
                ('specif', models.TextField(verbose_name='Спецификация')),
                ('bank_guar', models.BooleanField(choices=[(False, 'Нет'), (True, 'Да')], verbose_name='Банковская гарантия')),
                ('pledge', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сумма обеспечения')),
                ('kontragent', models.CharField(max_length=100, verbose_name='Контрагент')),
            ],
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=10, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reason', models.CharField(choices=[('1', 'Увеличение суммы'), ('-1', 'Уменьшение суммы'), ('some', 'Изменение условий'), ('cancell', 'Расторжение')], max_length=17, verbose_name='Причина изменения')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract', verbose_name='Контракт')),
            ],
        ),
        migrations.CreateModel(
            name='ContractNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(verbose_name='Номер')),
            ],
        ),
    ]
