# Generated by Django 2.1.7 on 2019-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractchange',
            name='reason',
            field=models.CharField(choices=[('1', 'Увеличение суммы'), ('-1', 'Уменьшение суммы'), ('some', 'Изменение условий'), ('cancell', 'Расторжение')], max_length=7, verbose_name='Причина изменения'),
        ),
    ]
