# Generated by Django 2.2.10 on 2020-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20190508_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='IkzNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(verbose_name='27-29 разряды ИКЗ')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='ikz',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='ИКЗ'),
        ),
    ]
