# Generated by Django 2.2.10 on 2020-03-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20200228_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfIkz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_27_29', models.PositiveIntegerField(verbose_name='27-29 разряды ИКЗ')),
                ('num_1_27_and_30_36', models.CharField(max_length=36, verbose_name='Остальная часть')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
            ],
        ),
        migrations.DeleteModel(
            name='IkzNum',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ikz',
        ),
        migrations.AddField(
            model_name='contract',
            name='part_of_ikz',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='27-29 разряды ИКЗ'),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_ikz_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.PartOfIkz', verbose_name='Остальная часть ИКЗ'),
        ),
    ]
