# Generated by Django 2.2.10 on 2020-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20200306_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='part_of_ikz',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='27-29 разряды ИКЗ (без нулей)'),
        ),
    ]
