# Generated by Django 2.1.7 on 2019-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikz', models.CharField(blank=True, max_length=36, verbose_name='ИКЗ')),
                ('num', models.CharField(max_length=19, unique=True, verbose_name='Номер извещения')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='НМЦК')),
                ('economy', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Экономия')),
                ('status', models.CharField(blank=True, choices=[('in_work', 'Закупка осуществляется'), ('done', 'Закупка завершена'), ('zero', 'Закупка не состоялась'), ('cancel', 'Закупка отменена')], db_index=True, default='in_work', max_length=20, verbose_name='Статус закупки')),
                ('smp', models.BooleanField(choices=[(False, 'Нет'), (True, 'Да')], verbose_name='Закупка для СМП')),
            ],
        ),
        migrations.CreateModel(
            name='TenderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Способ закупки')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Полное название способа закупки')),
                ('law', models.SmallIntegerField(choices=[(223, '223-ФЗ'), (44, '44-ФЗ')], db_index=True, verbose_name='Закон')),
                ('need_publicate', models.BooleanField(verbose_name='Нужно публиковать')),
                ('use_default_num', models.BooleanField(verbose_name='Генерировать номер')),
                ('sp_equal_cp', models.BooleanField(verbose_name='Способ закупки при котором НМЦК не меняется')),
            ],
        ),
    ]
