# Generated by Django 2.1.7 on 2019-05-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_auto_20190525_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendertype',
            name='full_name',
        ),
    ]
