# Generated by Django 2.2.9 on 2019-12-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_remove_tendertype_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='smp',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Закупка для СМП'),
        ),
    ]
