# Generated by Django 2.2.10 on 2020-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_auto_20191224_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendertype',
            name='ep_and_use_ikz',
            field=models.BooleanField(default=False, verbose_name='Генерировать ИКЗ'),
        ),
    ]
