# Generated by Django 2.2.10 on 2020-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_tendertype_ep_and_use_ikz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendertype',
            name='ep_and_use_ikz',
            field=models.BooleanField(default=False, verbose_name='Генерировать часть ИКЗ (ЕП до 300)'),
        ),
    ]
