# Generated by Django 2.2.10 on 2020-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_auto_20200306_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendertype',
            name='ep_and_use_ikz',
            field=models.BooleanField(default=False, verbose_name='Генерировать часть ИКЗ (ЕП до 600)'),
        ),
    ]
