# Generated by Django 3.0.6 on 2020-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предмет закупки')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата получения')),
                ('status', models.BooleanField(default=True, max_length=10, verbose_name='Статус')),
                ('year', models.ManyToManyField(db_index=True, to='limits.Limit', verbose_name='Годы лимитов')),
            ],
        ),
    ]
