# Generated by Django 2.2.3 on 2019-09-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190330_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='rating',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет закупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Worker', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='year',
            field=models.ManyToManyField(db_index=True, to='limits.Limit', verbose_name='Годы лимитов'),
        ),
    ]
