# Generated by Django 2.2.9 on 2019-12-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190913_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'username__in': ['Васильев', 'Луговская', 'Терехова', 'Чеботарев']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Worker', verbose_name='Ответственный'),
        ),
    ]
