# Generated by Django 2.2.10 on 2020-02-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20191224_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'username__in': ['Васильев', 'Луговская', 'Терехова', 'Чернышенко']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Worker', verbose_name='Ответственный'),
        ),
    ]
